package com.md.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHE_BEAN.
 */
public class CacheBean {

    /** Not-null value. */
    private String url;
    /** Not-null value. */
    private String json;

    public CacheBean() {
    }

    public CacheBean(String url) {
        this.url = url;
    }

    public CacheBean(String url, String json) {
        this.url = url;
        this.json = json;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    /** Not-null value. */
    public String getJson() {
        return json;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJson(String json) {
        this.json = json;
    }

}
