package com.md.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.md.bean.CacheBean;

import com.md.dao.CacheBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheBeanDaoConfig;

    private final CacheBeanDao cacheBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheBeanDaoConfig = daoConfigMap.get(CacheBeanDao.class).clone();
        cacheBeanDaoConfig.initIdentityScope(type);

        cacheBeanDao = new CacheBeanDao(cacheBeanDaoConfig, this);

        registerDao(CacheBean.class, cacheBeanDao);
    }
    
    public void clear() {
        cacheBeanDaoConfig.getIdentityScope().clear();
    }

    public CacheBeanDao getCacheBeanDao() {
        return cacheBeanDao;
    }

}
